### ISSUE TITLE
[Enhancement] Add a div with addtional information in the game page

### ISSUE THREAD

**Issue by qequ** [tryton-vanmeer/ProtonDB-for-Steam#30]
Hey I just was thinking about make a firefox extension showing the protondb rating of games and found your project, that it's just great!
Besides listing the trending proton rate I was thinking add a div on the right column of the steam game page, just like the steamdb extension does, to show;
* The most used proton version amongst the platinum and gold ratings
* Common used commands listed in ratings

I'm not sure if there are endpoints to get information for ratings, I've only found this [unofficial protondb api](https://protondb.max-p.me/) that it's not quite complete. Let me know what you think about adding those features.

Cheers!

**Comment by tryton-vanmeer** [comment]
The goal of my extension is to keep it simple, so this is a feature I won't add.

But I'm happy if you want to use mine as a base for your own.

The unofficial protondb api pulls from the uploaded protondb dump, so the data will likely always be about a month out of date. But it seems like the best way to do this since it is the full raw data, so you could parse out things like proton versions used.

I'm gonna close this issue, but feel free to keep the discussion going if you have any questions.
